* Hera

Hera (/ˈhɛrə, ˈhɪərə/; Greek: Ἥρᾱ Hērā, equivalently Ἥρη Hērē, in Ionic and Homer) is
the goddess of women and marriage in Greek mythology and religion. She is the
daughter of the Titans Cronus and Rhea.

Slain by Hercules, Hera created the [[https://github.com/abo-abo/hydra][Hydra]] constellation.

This package provides three major features:

- Register major-mode specific Hydras
- Designate a default Hydra
- A stack-based API for nested Hydras

** api

*** hera-register MAJOR-MODE HYDRA-BODY

Register HYDRA-BODY as the Hydra for MAJOR-MODE.

*** hera-push HYDRA-BODY

Push HYDRA-BODY onto the Hera stack, then execute it.

*** hera-pop

Pop a Hydra from the Hera stack, then execute it. Close Hydra if stack is empty.

*** hera-run

Execute the Hydra for the current major-mode or =hera-default-hydra=

** configuration

*** hera-default-hydra

The default Hydra body when none is specified for the current major-mode.

*** keybindings

#+begin_src emacs-lisp
(global-set-key (kbd "<f19>") 'hera-run)
(global-set-key (kbd "C-<f19>") 'hera-pop)
#+end_src
